1.
throw without exception

2.
No, because what is thrown is 'double'.

3.
add exception handling codes for new failure in genMino.cpp

g++ -c tetris5.cpp
g++ -c genMino.cpp
g++ -c Mino.cpp
g++ -c MinoI.cpp
g++ -c MinoS.cpp
g++ -c MinoL.cpp
g++ -c MinoO.cpp
g++ -c MinoT.cpp
g++ -o tetris5 tetris5.o genMino.o Mino.o MinoI.o MinoS.o MinoL.o MinoO.o MinoT.o


